# Generated by Django 3.2.25 on 2025-04-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
